/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileInputStream;
import java.io.ObjectOutputStream;
import java.io.ObjectInputStream;
import java.io.PrintWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.net.InetAddress;
import java.util.ArrayList;

/**
 *
 * @author Илья
 */
public class tabs extends javax.swing.JFrame {
 
    private java.util.List<RecIntegral> list = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tabs.class.getName());
    private TcpServer server;
    /**
     * Creates new form tabs
     */
    public tabs() {
        initComponents();
        
        button_calculate.addActionListener(this::button_calculate);
        
                
        server = new TcpServer(6000);
        server.listenForClients();
                // Синхронизация таблицы и коллекции
        jTable1.getModel().addTableModelListener(e -> {
            int row = e.getFirstRow();
            int col = e.getColumn();

            if (row < 0 || col < 0) return;

            // Получаем ID строки
            int id = (int) jTable1.getValueAt(row, 0);

            // Ищем объект в коллекции
            RecIntegral rec = null;
            for (RecIntegral r : list) {
                if (r.id == id) {
                    rec = r;
                    break;
                }
            }

            if (rec == null) return;

            // Обновляем поля объекта
            switch (col) {
                case 1 -> rec.a = Double.parseDouble(jTable1.getValueAt(row, 1).toString());
                case 2 -> rec.b = Double.parseDouble(jTable1.getValueAt(row, 2).toString());
                case 3 -> rec.h = Double.parseDouble(jTable1.getValueAt(row, 3).toString());
                case 4 -> rec.result = Double.parseDouble(jTable1.getValueAt(row, 4).toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        button_add = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_calculate = new javax.swing.JButton();
        func_text = new javax.swing.JLabel();
        table_result = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        text_high_line = new javax.swing.JLabel();
        text_low_line = new javax.swing.JLabel();
        text_step = new javax.swing.JLabel();
        textfield_lowline = new javax.swing.JTextField();
        textfield_highline = new javax.swing.JTextField();
        textfield_step = new javax.swing.JTextField();
        button_add_collection = new javax.swing.JButton();
        button_delete_collection = new javax.swing.JButton();
        button_save_text = new javax.swing.JButton();
        button_load_text = new javax.swing.JButton();
        button_save_binary = new javax.swing.JButton();
        button_load_binary = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setSize(new java.awt.Dimension(452, 420));

        button_add.setText("Добавить ");
        button_add.addActionListener(this::button_add);

        button_delete.setText("Удалить");
        button_delete.addActionListener(this::button_deleteActionPerformed);

        button_calculate.setText("Вычислить");
        button_calculate.addActionListener(this::button_calculateActionPerformed);

        func_text.setText("1/x");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "НП", "ВП", "Шаг", "Результат"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_result.setViewportView(jTable1);

        text_high_line.setText("Верхний порог ");

        text_low_line.setText("Нижний порог");

        text_step.setText("Шаг");

        textfield_lowline.addActionListener(this::textfield_lowlineActionPerformed);

        textfield_highline.addActionListener(this::textfield_highlineActionPerformed);

        button_add_collection.setText("Восстановить из коллекции");
        button_add_collection.addActionListener(this::button_add_collectionActionPerformed);

        button_delete_collection.setText("Очистить таблицу");
        button_delete_collection.addActionListener(this::button_delete_collectionActionPerformed);

        button_save_text.setText("Сохранить в txt");
        button_save_text.addActionListener(this::button_save_textActionPerformed);

        button_load_text.setText("Загрузить из txt");
        button_load_text.addActionListener(this::button_load_textActionPerformed);

        button_save_binary.setText("Сохранить в бинарный файл");
        button_save_binary.addActionListener(this::button_save_binaryActionPerformed);

        button_load_binary.setText("Загрузить из бинарного файла");
        button_load_binary.addActionListener(this::button_load_binaryActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(table_result)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_low_line)
                            .addComponent(text_step)
                            .addComponent(text_high_line))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfield_highline, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(textfield_step)
                            .addComponent(textfield_lowline)))
                    .addComponent(func_text))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_delete_collection, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_add_collection)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_load_binary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_save_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_load_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_save_binary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_calculate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(func_text)
                    .addComponent(button_save_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_high_line)
                            .addComponent(button_load_text))
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button_add)
                            .addComponent(textfield_highline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_low_line)
                            .addComponent(textfield_lowline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_delete))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_step)
                            .addComponent(textfield_step, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_calculate)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_save_binary)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_load_binary)))
                .addGap(18, 18, 18)
                .addComponent(button_add_collection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_delete_collection)
                .addGap(18, 18, 18)
                .addComponent(table_result, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1){

            int id = (int) jTable1.getValueAt(selectedRow, 0);

            RecIntegral toRemove = null;
            for (RecIntegral r : list) {
                if (r.id == id) {
                    toRemove = r;
                    break;
                }
            }
            if (toRemove != null) {
                list.remove(toRemove);
            }

            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Choose, delete row!");
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_add(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add
        try {
            double a, b, h;

            try {
                a = Double.parseDouble(textfield_lowline.getText());
            } catch (NumberFormatException e) {
                throw new InvalidException("Введите корректное число", "Нижний порог", textfield_lowline.getText());
            }

            try {
                b = Double.parseDouble(textfield_highline.getText());
            } catch (NumberFormatException e) {
                throw new InvalidException("Введите корректное число", "Верхний порог", textfield_highline.getText());
            }

            try {
                h = Double.parseDouble(textfield_step.getText());
            } catch (NumberFormatException e) {
                throw new InvalidException("Введите корректное число", "Шаг", textfield_step.getText());
            }
            
            if (a < 0.000001 || a > 1_000_000)
                throw new InvalidException("Значение вне диапазона 0.000001 – 1 000 000", "Нижний порог", String.valueOf(a));

            if (b < 0.000001 || b > 1_000_000)
                throw new InvalidException("Значение вне диапазона 0.000001 – 1 000 000", "Верхний порог", String.valueOf(b));

            if (h <= 0)
                throw new InvalidException("Шаг должен быть больше 0", "Шаг", String.valueOf(h));

            if (h > b - a)
                throw new InvalidException("Шаг превышает интервал интегрирования", "Шаг", String.valueOf(h));

            if (a >= b)
                throw new InvalidException("Нижний порог должен быть меньше верхнего", "Нижний порог", String.valueOf(a));

            RecIntegral rec = new RecIntegral(a, b, h, 0);
            list.add(rec);

            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();

            model.addRow(new Object[]{rec.id, a, b, h, 0});

        } catch (InvalidException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ошибка в поле: " + ex.getFieldName() +
                    "\nВведено: " + ex.getWrongValue() +
                    "\n" + ex.getMessage(),
                    "Ошибка данных",
                    JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_button_add

    private void textfield_highlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_highlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_highlineActionPerformed

    private void textfield_lowlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_lowlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_lowlineActionPerformed

    private void button_delete_collectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_collectionActionPerformed
        javax.swing.table.DefaultTableModel model = 
                (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);        
        // TODO add your handling code here:
    }//GEN-LAST:event_button_delete_collectionActionPerformed

    private void button_add_collectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_collectionActionPerformed
         javax.swing.table.DefaultTableModel model=(javax.swing.table.DefaultTableModel) jTable1.getModel();
        //model.setRowCount(0);
        refreshTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_button_add_collectionActionPerformed

    private void button_save_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_save_textActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();

            try (PrintWriter pw = new PrintWriter(file)) {
                for (RecIntegral r : list) {
                    pw.println(r.id + ";" + r.a + ";" + r.b + ";" + r.h + ";" + r.result);
                }
                JOptionPane.showMessageDialog(this, "Сохранено в текстовый файл!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ошибка сохранения: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_button_save_textActionPerformed

    private void button_save_binaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_save_binaryActionPerformed
        // TODO add your handling code here:                                                                                          
        JFileChooser chooser = new JFileChooser();
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();

            try (ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(file))) {
                out.writeObject(list);
                JOptionPane.showMessageDialog(this, "Сохранено в бинарный файл!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ошибка сохранения: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_button_save_binaryActionPerformed

    private void button_load_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_load_textActionPerformed
        // TODO add your handling code here:
               JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();

            list.clear();

            try (BufferedReader br = new BufferedReader(new FileReader(file))) {
                String line;
                while ((line = br.readLine()) != null) {
                    String[] p = line.split(";");

                    RecIntegral r = new RecIntegral(
                            Double.parseDouble(p[1]),
                            Double.parseDouble(p[2]),
                            Double.parseDouble(p[3]),
                            Double.parseDouble(p[4])
                    );
                    r.id = Integer.parseInt(p[0]);
                    list.add(r);
                }

                // обновляем counter, чтобы ID не повторялись
                RecIntegral.counter = list.stream()
                        .mapToInt(r -> r.id)
                        .max()
                        .orElse(0) + 1;

                refreshTable();
                JOptionPane.showMessageDialog(this, "Загружено из текстового файла!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ошибка загрузки: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_button_load_textActionPerformed

    private void button_load_binaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_load_binaryActionPerformed
        // TODO add your handling code here:                                              
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();

            try (ObjectInputStream in = new ObjectInputStream(new FileInputStream(file))) {
                list = (ArrayList<RecIntegral>) in.readObject();

                // обновляем counter
                RecIntegral.counter = list.stream()
                        .mapToInt(r -> r.id)
                        .max()
                        .orElse(0) + 1;

                refreshTable();
                JOptionPane.showMessageDialog(this, "Загружено из бинарного файла!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Ошибка загрузки: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_button_load_binaryActionPerformed

    private void button_calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_calculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_calculateActionPerformed
        
    private void button_calculate(java.awt.event.ActionEvent evt) {
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Choose Row!");
            return;
        }

        // вычисление в отдельном потоке
        new Thread(() -> {
            try {
                RecIntegral rec = list.get(selectedRow);

                double a = rec.a;
                double b = rec.b;
                double h = rec.h;
                
                double total = server.calculateDistributed(a, b, h);

                rec.result = total;
                
                javax.swing.SwingUtilities.invokeLater(() -> {
                    javax.swing.table.DefaultTableModel model =
                            (javax.swing.table.DefaultTableModel) jTable1.getModel();
                    model.setValueAt(total, selectedRow, 4);
                });

            } catch (Exception e) {
                javax.swing.SwingUtilities.invokeLater(() ->
                        JOptionPane.showMessageDialog(this, "Calculation error: " + e.getMessage())
                );
            }
        }).start();
}


    private void refreshTable() {
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.setRowCount(0);

    for (RecIntegral r : list) {
        model.addRow(new Object[]{
                r.id,
                r.a,
                r.b,
                r.h,
                r.result
        });
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            

        java.awt.EventQueue.invokeLater(() -> new tabs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_add_collection;
    private javax.swing.JButton button_calculate;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_delete_collection;
    private javax.swing.JButton button_load_binary;
    private javax.swing.JButton button_load_text;
    private javax.swing.JButton button_save_binary;
    private javax.swing.JButton button_save_text;
    private javax.swing.JLabel func_text;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane table_result;
    private javax.swing.JLabel text_high_line;
    private javax.swing.JLabel text_low_line;
    private javax.swing.JLabel text_step;
    private javax.swing.JTextField textfield_highline;
    private javax.swing.JTextField textfield_lowline;
    private javax.swing.JTextField textfield_step;
    // End of variables declaration//GEN-END:variables
}
