/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

/**
 *
 * @author Илья
 */
public class tabs extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tabs.class.getName());

    /**
     * Creates new form tabs
     */
    public tabs() {
        initComponents();
        button_calculate.addActionListener(this::button_calculate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        button_add = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_calculate = new javax.swing.JButton();
        func_text = new javax.swing.JLabel();
        table_result = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        text_high_line = new javax.swing.JLabel();
        text_low_line = new javax.swing.JLabel();
        text_step = new javax.swing.JLabel();
        textfield_lowline = new javax.swing.JTextField();
        textfield_highline = new javax.swing.JTextField();
        textfield_step = new javax.swing.JTextField();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setSize(new java.awt.Dimension(452, 420));

        button_add.setText("Добавить ");
        button_add.addActionListener(this::button_add);

        button_delete.setText("Удалить");
        button_delete.addActionListener(this::button_deleteActionPerformed);

        button_calculate.setText("Вычислить");

        func_text.setText("1/x");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "НП", "ВП", "Шаг", "Результат"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_result.setViewportView(jTable1);

        text_high_line.setText("Верхний порог ");

        text_low_line.setText("Нижний порог");

        text_step.setText("Шаг");

        textfield_lowline.addActionListener(this::textfield_lowlineActionPerformed);

        textfield_highline.addActionListener(this::textfield_highlineActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(table_result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(func_text)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_low_line)
                            .addComponent(text_step)
                            .addComponent(text_high_line))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfield_highline, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(textfield_step)
                            .addComponent(textfield_lowline))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(button_calculate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(func_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_high_line)
                    .addComponent(textfield_highline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_add))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_low_line)
                    .addComponent(textfield_lowline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_step)
                    .addComponent(textfield_step, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_calculate))
                .addGap(37, 37, 37)
                .addComponent(table_result, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1){
            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);
        }else {
            javax.swing.JOptionPane.showMessageDialog(this, "Choose, delete row!");
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_add(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add
        try {
            String np = textfield_lowline.getText();
            String vp = textfield_highline.getText();
            String step = textfield_step.getText();
            
            javax.swing.table.DefaultTableModel model = 
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{np, vp, step, ""});
            
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(this,"Error, no correct data!");
        }
        
    }//GEN-LAST:event_button_add

    private void textfield_highlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_highlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_highlineActionPerformed

    private void textfield_lowlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_lowlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_lowlineActionPerformed
    
    public class RecIntegral {
        
    }
    
    private void button_calculate(java.awt.event.ActionEvent evt) {
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {
        try {
            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();

            double a = Double.parseDouble(model.getValueAt(selectedRow, 0).toString());
            double b = Double.parseDouble(model.getValueAt(selectedRow, 1).toString());
            double h = Double.parseDouble(model.getValueAt(selectedRow, 2).toString());

            if (a <= 0 || b <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "1/x undefined at x <= 0!");
                return;
            }

            double result = calculateIntegral(a, b, h);

            
            model.setValueAt(result, selectedRow, 3);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Calculation error!");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Choose Row!");
    }
}

    private double calculateIntegral(double a, double b, double h) {
    if (h <= 0) {
        throw new IllegalArgumentException("Step must be > 0");
    }

    double sum = 0.0;
    double x = a;

    while (x < b) {

        double x1 = x;
        double x2 = x + h;

       
        if (x2 > b) {
            x2 = b;
        }

        if (x1 == 0 || x2 == 0) {
            throw new IllegalArgumentException("1/x undefined at x = 0");
        }

        double step = x2 - x1;

        sum += (1.0 / x1 + 1.0 / x2) / 2.0 * step;

        x = x2;
    }
    
    return sum;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            

        java.awt.EventQueue.invokeLater(() -> new tabs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_calculate;
    private javax.swing.JButton button_delete;
    private javax.swing.JLabel func_text;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane table_result;
    private javax.swing.JLabel text_high_line;
    private javax.swing.JLabel text_low_line;
    private javax.swing.JLabel text_step;
    private javax.swing.JTextField textfield_highline;
    private javax.swing.JTextField textfield_lowline;
    private javax.swing.JTextField textfield_step;
    // End of variables declaration//GEN-END:variables
}
