/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication2;

/**
 *
 * @author Илья
 */
public class tabs extends javax.swing.JFrame {
 
    private java.util.List<RecIntegral> list = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tabs.class.getName());
    /**
     * Creates new form tabs
     */
    public tabs() {
        initComponents();
        button_calculate.addActionListener(this::button_calculate);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        button_add = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_calculate = new javax.swing.JButton();
        func_text = new javax.swing.JLabel();
        table_result = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        text_high_line = new javax.swing.JLabel();
        text_low_line = new javax.swing.JLabel();
        text_step = new javax.swing.JLabel();
        textfield_lowline = new javax.swing.JTextField();
        textfield_highline = new javax.swing.JTextField();
        textfield_step = new javax.swing.JTextField();
        button_add_collection = new javax.swing.JButton();
        button_delete_collection = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setSize(new java.awt.Dimension(452, 420));

        button_add.setText("Добавить ");
        button_add.addActionListener(this::button_add);

        button_delete.setText("Удалить");
        button_delete.addActionListener(this::button_deleteActionPerformed);

        button_calculate.setText("Вычислить");

        func_text.setText("1/x");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "НП", "ВП", "Шаг", "Результат"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_result.setViewportView(jTable1);

        text_high_line.setText("Верхний порог ");

        text_low_line.setText("Нижний порог");

        text_step.setText("Шаг");

        textfield_lowline.addActionListener(this::textfield_lowlineActionPerformed);

        textfield_highline.addActionListener(this::textfield_highlineActionPerformed);

        button_add_collection.setText("Восстановить из коллекции");
        button_add_collection.addActionListener(this::button_add_collectionActionPerformed);

        button_delete_collection.setText("Очистить таблицу");
        button_delete_collection.addActionListener(this::button_delete_collectionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_low_line)
                            .addComponent(text_step)
                            .addComponent(text_high_line))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfield_highline, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(textfield_step)
                            .addComponent(textfield_lowline)))
                    .addComponent(func_text))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_delete_collection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_add_collection, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_calculate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addComponent(table_result)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(func_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_high_line)
                    .addComponent(textfield_highline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_add)
                    .addComponent(button_add_collection))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_low_line)
                    .addComponent(textfield_lowline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_delete)
                    .addComponent(button_delete_collection))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_step)
                    .addComponent(textfield_step, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_calculate))
                .addGap(37, 37, 37)
                .addComponent(table_result, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow != -1){

            int id = (int) jTable1.getValueAt(selectedRow, 0);

            RecIntegral toRemove = null;
            for (RecIntegral r : list) {
                if (r.id == id) {
                    toRemove = r;
                    break;
                }
            }
            if (toRemove != null) {
                list.remove(toRemove);
            }

            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Choose, delete row!");
        }
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_add(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add
        try {
            double a = Double.parseDouble(textfield_lowline.getText());
            double b = Double.parseDouble(textfield_highline.getText());
            double h = Double.parseDouble(textfield_step.getText());
            
                    // Проверка диапазона
            if (a < 0.000001 || a > 1_000_000 ||
                b < 0.000001 || b > 1_000_000 ||
                h < 0.000001 || h > 1_000_000) {

                throw new InvalidException(
                        "Значения должны быть в диапазоне 0.000001 – 1 000 000"
                );
            }

            // Проверка, что a < b
            if (a >= b) {
                throw new InvalidException(
                        "Нижний порог должен быть меньше верхнего"
                );
            }

            // Проверка шага
            if (h <= 0) {
                throw new InvalidException(
                        "Шаг должен быть больше 0"
                );
            }
            
            //шаг превышает интервал интегрирования
            if (h > b - a){
                throw new InvalidException(
                        "Шаг первышает интервал интегрирования"
                );
            }
            
            
            RecIntegral rec = new RecIntegral(a,b,h,0);
            list.add(rec);
            javax.swing.table.DefaultTableModel model = 
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{rec.id,a,b,h,0});

            
        } catch (InvalidException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Ошибка данных",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_button_add

    private void textfield_highlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_highlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_highlineActionPerformed

    private void textfield_lowlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield_lowlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield_lowlineActionPerformed

    private void button_delete_collectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_delete_collectionActionPerformed
        javax.swing.table.DefaultTableModel model = 
                (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);        
        // TODO add your handling code here:
    }//GEN-LAST:event_button_delete_collectionActionPerformed

    private void button_add_collectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_add_collectionActionPerformed
         javax.swing.table.DefaultTableModel model=(javax.swing.table.DefaultTableModel) jTable1.getModel();
        //model.setRowCount(0);
        refreshTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_button_add_collectionActionPerformed
        
    private void button_calculate(java.awt.event.ActionEvent evt) {
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {
        try {
            javax.swing.table.DefaultTableModel model =
                    (javax.swing.table.DefaultTableModel) jTable1.getModel();
        

            RecIntegral rec = list.get(selectedRow);
            double result = rec.calculate();                  
            model.setValueAt(result, selectedRow, 4);
            

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Calculation error!");
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Choose Row!");
    }
}

    private void refreshTable() {
    javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    model.setRowCount(0); // очищаем таблицу

    for (RecIntegral r : list) {
        model.addRow(new Object[]{
                r.id,
                r.a,
                r.b,
                r.h,
                r.result
        });
    }
}


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            

        java.awt.EventQueue.invokeLater(() -> new tabs().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_add;
    private javax.swing.JButton button_add_collection;
    private javax.swing.JButton button_calculate;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_delete_collection;
    private javax.swing.JLabel func_text;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane table_result;
    private javax.swing.JLabel text_high_line;
    private javax.swing.JLabel text_low_line;
    private javax.swing.JLabel text_step;
    private javax.swing.JTextField textfield_highline;
    private javax.swing.JTextField textfield_lowline;
    private javax.swing.JTextField textfield_step;
    // End of variables declaration//GEN-END:variables
}
